server:
  port: 8081

spring:
  profiles.active: local

liquibase:
  change-log: classpath:/database/changelog/db.changelog-master.yaml
  enabled: true
  drop-first: true
  contexts: local

---

spring:
  profiles: local
  datasource:
    driver: org.h2.Driver
    url: jdbc:h2:~/testdb
    username: sa
    password:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
        hibernate.hbm2ddl.auto: update
